docs
bit-docs/bit-docs-js pull request #5
Opened 2017-04-18 04:01 UTC by leoj3n

WIP, feedback welcome.

2017-05-11 17:32 UTC, chasenlehara requested changes
👍

2017-05-11 17:32 UTC, chasenlehara commented on tags/function.js
> +namedFunction = /\s*function\s+([\w\.\$]+)\s*(~)?\(([^\)]*)/;
Now that these aren’t comma-separated, they should have a `var` declaration.

2017-05-11 17:34 UTC, chasenlehara commented
In the future, I wouldn’t worry about cleaning up the code. 😊 It’s hard to see what docs were actually changed when there are a bunch of other changes in the code.

2017-05-11 18:06 UTC, leoj3n commented
I agree it's hard to see on the overall PR. I tried to make a compromise by though by doing doc changes and formatting changes in separate commits. I guess that means you have to step through individual commits which isn't optimal. What do you think is the best way to handle code that could really use some formatting love, but also needs editing?

Kind of a chicken/egg problem. 🐣

We can:

1. Wait for edits to get merged with bad formatting before reformatting...
2. Wait for reformatting to get merged before making edits...
3. Have both in one PR but on separate commits like they are here.

Being able to make edits is most important, so wouldn't want to be waiting on formatting long.

2017-05-11 18:16 UTC, leoj3n commented
Reading your comment again @chasenlehara — I guess you're saying don't reformat the code at all.

I'm cool with that. I think I was paranoid the docs weren't being built correctly at one point due to the crazy formatting with mixed tabs/spaces in front of comment blocks, and I reformatted because of that (but that wasn't the issue after all). It was also harder to follow the code before reformatting, but I certainly could have got by without touching the formatting.

For these files it might be a bit of a hassle for me to undo the formatting, so hopefully can keep them how they are in this PR, but I'll try not to touch any formatting in other files.

2017-05-11 20:28 UTC, chasenlehara commented
I would wait to reformat stuff until we add ESLint to our projects, but if you come across stuff that’s so bad it’s unreadable, go ahead and fix it and submit it as a PR. You can still branch off a formatting branch to make documentation changes and submit those as a separate PR.

2017-05-12 02:17 UTC, leoj3n commented
Okay, that makes sense.

On May 11, 2017 3:28 PM, "Chasen Le Hara" <notifications@github.com> wrote:

> I would wait to reformat stuff until we add ESLint to our projects, but if
> you come across stuff that’s so bad it’s unreadable, go ahead and fix it
> and submit it as a PR. You can still branch off a formatting branch to make
> documentation changes and submit those as a separate PR.
>
> —
> You are receiving this because you were assigned.
> Reply to this email directly, view it on GitHub
> <https://github.com/bit-docs/bit-docs-js/pull/5#issuecomment-300907757>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AA8cCAsl95B26Z-8NQwk1dQHBlo1hYiiks5r429igaJpZM4M_2B3>
> .
>

2017-05-26 17:44 UTC, chasenlehara approved these changes

2017-05-26 17:47 UTC, merged